spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:1111/realms/dev
      client:
        registration:
          keycloak:
            client-id: fbp
            client-secret: JxYYv7zap2uhHNWFii3ET8LRvx2RdJWh
            scope: openid,profile,email
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://localhost:1111/realms/dev
            user-name-attribute: preferred_username
  flyway:
    user: fbp
    password: fbp
    schemas: fbp
    url: jdbc:postgresql://localhost:5432/fbp
  datasource:
    url: jdbc:postgresql://localhost:5432/fbp
    username: fbp
    password: fbp
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000ms
      password: 1234
      username: redis
keycloak:
  server-url: http://localhost:1111
  realm: dev
  username: admin
  password: password
server:
  port: 8081
