version: '3.8'

services:
  postgres:
    image: postgres:12
    container_name: fbp-postgres-container
    environment:
      POSTGRES_DB: fbp
      POSTGRES_USER: fbp
      POSTGRES_PASSWORD: fbp
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    container_name: fbp-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-config.json
      KC_HTTP_ENABLED: "true"
    ports:
      - "1111:8080"
    volumes:
      - ./realm-config.json:/opt/keycloak/data/import/realm-config.json
    command: ["start-dev", "--import-realm"]
